---
- name: Remove entities for k8s cluster from each node
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/kubernetes"
    - "~/.kube"
    - "/etc/cni"
    - "/var/lib/kubelet"
    - "/var/lib/etcd"
    - "/var/run/kubernetes"
    - "/var/lib/dockershim"
