- name: Upload files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'k8s.conf', dest: '/etc/sysctl.d/k8s.conf'}
    - { src: '99-kubernetes-cri.conf', dest: '/etc/sysctl.d/99-kubernetes-cri.conf'}

- name: Restart sysctl
  shell: |
    sysctl --system
  tags: skip_ansible_lint
