
---
- name: Init vars
  set_fact:
    host_lines: |
      {% for node in groups['cluster'] %}
      {{ hostvars[node]['ansible_host'] }} {{ hostvars[node]['inventory_hostname'] }}
      {% endfor %}

- name: Add new records to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    state: absent
  with_items: "{{ host_lines }}"
