---
- name: Copy manifest for flannel
  copy:
    src: kube-flannel.yml
    dest: '/tmp/kube-flannel.yml'
    owner: "{{ manageuser | default('k8smanager') }}"

- name: Apply flannel network resource for k8s cluster
  shell: |
    kubectl apply -f '/tmp/kube-flannel.yml'
  become_user: "{{ manageuser | default('k8smanager') }}"
  tags: skip_ansible_lint
