---
- name: Run firewalld service
  service:
    name: firewalld
    state: started
  register: firewalldout

- name: Unsuccess running FirewallD
  fail:
     msg: "FirewallD can`t run"
  when: firewalldout.status['SubState'] != "running"

- name: Modify firewall rules
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 10251/tcp
    - 10252/tcp
    - 10255/tcp
    - 8472/udp
    - 30000-32767/tcp
  when: firewalldout.status['SubState'] == "running"

- name: Add masquerade
  firewalld:
    masquerade: yes
    state: enabled
    permanent: yes
  when: firewalldout.status['SubState'] == "running"

- name: reStarting firewalld service
  service:
    name: firewalld
    state: restarted
